version: '3'
services:
  db:
    image: library/postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  app:
    build:
      ./app

    restart: always