FROM python:3.8.3-alpine
# set work directory
WORKDIR /usr/src/app
# set environment variables
ENV LIGA_TAXI_TOKEN=1425899358:AAG12T7DmN4PGpmMu3oyu4zeITRm21QV41I
ENV DBNAME=postgres
ENV DBUSER=postgres
ENV DBPASSWORD=secret
# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev
# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .
RUN python3.8 main.py



